CREATE DATABASE sistema_lan_house;
USE sistema_lan_house;

CREATE TABLE CLIENTE (
    cpf VARCHAR(14) NOT NULL,
    nome VARCHAR(45) NOT NULL,
    telefone VARCHAR(20),
    PRIMARY KEY (cpf)
);

CREATE TABLE ENDERECO (
    idENDERECO INT NOT NULL AUTO_INCREMENT,
    bairro VARCHAR(45),
    rua VARCHAR(45),
    numero INT,
    cep VARCHAR(45),
    cpf_CLIENTE VARCHAR(14) NOT NULL,
    PRIMARY KEY (idENDERECO),
    FOREIGN KEY (cpf_CLIENTE) REFERENCES CLIENTE(cpf)
);

CREATE TABLE COMPUTADORES (
    idCOMPUTADORES INT NOT NULL AUTO_INCREMENT,
    numero_computador INT NOT NULL,
    PRIMARY KEY (idCOMPUTADORES)
);

CREATE TABLE SESSAO (
    idSESSAO INT NOT NULL AUTO_INCREMENT,
    numero_sessao INT NOT NULL,
    cpf_CLIENTE VARCHAR(14) NOT NULL,
    id_COMPUTADORES INT NOT NULL,
    PRIMARY KEY (idSESSAO),
    FOREIGN KEY (cpf_CLIENTE) REFERENCES CLIENTE(cpf),
    FOREIGN KEY (id_COMPUTADORES) REFERENCES COMPUTADORES(idCOMPUTADORES)
);

CREATE TABLE PRODUTO (
    idPRODUTO INT NOT NULL AUTO_INCREMENT,
    nome_produto VARCHAR(45) NOT NULL,
    valor_produto DECIMAL(8,2) NOT NULL,
    PRIMARY KEY (idPRODUTO)
);

CREATE TABLE CONSUMO (
    idCONSUMO INT NOT NULL AUTO_INCREMENT,
    quantidade INT NOT NULL,
    cpf_CLIENTE VARCHAR(14) NOT NULL,
    id_PRODUTO INT NOT NULL,
    PRIMARY KEY (idCONSUMO),
    FOREIGN KEY (cpf_CLIENTE) REFERENCES CLIENTE(cpf),
    FOREIGN KEY (id_PRODUTO) REFERENCES PRODUTO(idPRODUTO)
);

CREATE TABLE TORNEIO (
    idTORNEIO INT NOT NULL AUTO_INCREMENT,
    data DATE NOT NULL,
    hora TIME NOT NULL,
    PRIMARY KEY (idTORNEIO)
);

CREATE TABLE INSCRICOES (
    idINSCRICOES INT NOT NULL AUTO_INCREMENT,
    data_inscricao DATE NOT NULL,
    valor_inscricao DECIMAL(8,2) NOT NULL,
    cpf_CLIENTE VARCHAR(14) NOT NULL,
    id_TORNEIO INT NOT NULL,
    PRIMARY KEY (idINSCRICOES),
    FOREIGN KEY (cpf_CLIENTE) REFERENCES CLIENTE(cpf),
    FOREIGN KEY (id_TORNEIO) REFERENCES TORNEIO(idTORNEIO)
);
